### PR TITLE
update applications to include voice

### PR DESCRIPTION
**Pull request by dtolb**
Updates applications with new voice information

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-voice-info-to-applications.s3-website-us-east-1.amazonaws.com/

**Review by jmulford-bw — APPROVED** [review]

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-voice-info-to-applications.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-voice-info-to-applications.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-voice-info-to-applications.s3-website-us-east-1.amazonaws.com/

**Pull request merged**
