### PR TITLE
Bwdb 10677

### PR DESCRIPTION
**Pull request by jhough07**
## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `stop-gap-v2`

## Brief Summary of changes

Updating the POST /tnoptions documentation to be specific for A2P Campaigns, and give clear directions on how to see complete REST API documentation.

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-bwdb-10677.s3-website-us-east-1.amazonaws.com/index.html

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-bwdb-10677.s3-website-us-east-1.amazonaws.com/index.html

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-bwdb-10677.s3-website-us-east-1.amazonaws.com/index.html

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-bwdb-10677.s3-website-us-east-1.amazonaws.com/index.html

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-bwdb-10677.s3-website-us-east-1.amazonaws.com/index.html

**Review by jmulford-bw — APPROVED** [review]
Obviously I'm not an expert on your API, so I'm approving from a layout/format perspective

**Pull request merged**
