### PR TITLE
Guide to the guides

### PR DESCRIPTION
**Pull request by troft**

### CODE REVIEW

**Comment by dtolb** [comment]
Preview Changes at:
        http://bw-dev-guideToTheGuides.s3-website-us-east-1.amazonaws.com/

**Comment by dtolb** [comment]
Preview Changes at:
        http://bw-dev-guideToTheGuides.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-guideToTheGuides.s3-website-us-east-1.amazonaws.com/

**Review by jkgibbs — APPROVED** [review]

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-guideToTheGuides.s3-website-us-east-1.amazonaws.com/

**Pull request merged**
