### PR TITLE
TDP-5022 improve recording docs

### PR DESCRIPTION
**Pull request by rmello-daitan**
## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `stop-gap-v2`

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-tdp-5022-improve-recording-docs.s3-website-us-east-1.amazonaws.com/index.html

**Comment by muesono-daitan** [comment]
You could refer the `bxmlRecording` page as well, at `Voice > Guides & Tutorials > BXML Recording`.

**Comment by rmello-daitan** [comment]
It sucks that I can't link stuff in that blue info box @mhossomi talked about :disappointed:

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-tdp-5022-improve-recording-docs.s3-website-us-east-1.amazonaws.com/index.html

**Review by marcelohossomi — APPROVED** [review]

**Review by muesono-daitan — APPROVED** [review]

**Pull request merged**
