### PR TITLE
add node code

### PR DESCRIPTION
**Pull request by dtolb**
## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `stop-gap-v2`

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-954-add-node-to-guide.s3-website-us-east-1.amazonaws.com/

**Comment by dtolb** [comment]
Review specifically : http://bw-dev-dx-954-add-node-to-guide.s3-website-us-east-1.amazonaws.com/numbers/guides/csrLookup.html

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-954-add-node-to-guide.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-954-add-node-to-guide.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-954-add-node-to-guide.s3-website-us-east-1.amazonaws.com/

**Review by jmulford-bw — APPROVED** [review]

**Pull request merged**
