### PR TITLE
more verbose error documentation

### PR DESCRIPTION
**Pull request by dtolb**
Better voice error docs

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-603-better-voice-errors.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-603-better-voice-errors.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-603-better-voice-errors.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-603-better-voice-errors.s3-website-us-east-1.amazonaws.com/

**Review by perrismith — APPROVED** [review]
Looks great to me! This is super helpful. Thanks!

**Review by jchavez443 — APPROVED** [review]

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-603-better-voice-errors.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-603-better-voice-errors.s3-website-us-east-1.amazonaws.com/

**Pull request merged**
