### PR TITLE
Emergency Services in dev

### PR DESCRIPTION
**Pull request by dtolb**
## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `stop-gap-v2`

## Brief Summary of changes

* Brings in emergency services (with the one guide)
* re-arranges the SDKs/Dev Tools up at the top
* moves Links to top of the SDK pages 
* Links out to Iris SDKs

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-emergency-services.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-emergency-services.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-emergency-services.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-emergency-services.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-emergency-services.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-emergency-services.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-emergency-services.s3-website-us-east-1.amazonaws.com/

**Review by jmulford-bw — APPROVED** [review]
The guide gets a little hard to follow in a few sections. Did we make a http/sdk page that shows a walkthrough? I think linking that in this guide would help

**Comment by dtolb** [comment]
> The guide gets a little hard to follow in a few sections. Did we make a http/sdk page that shows a walkthrough? I think linking that in this guide would help

No walk-thru guide yet. Wanted to get this out first. But good call, creating that card now 🤔

**Pull request merged**
