### PR TITLE
Update node.md

### PR DESCRIPTION
**Pull request by jmulford-bw**
## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `stop-gap-v2`

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-node-gather-release.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-node-gather-release.s3-website-us-east-1.amazonaws.com/

**Review by dtolb — CHANGES_REQUESTED** [review]
Missing a commit?

**Comment by jmulford-bw** [comment]
@dtolb this was just for the gather release we did earlier this week

**Comment by dtolb** [comment]
Gotcha, the empty tables don't look so good. Let's wait to merge this one until we get to DX-1106

**Comment by jmulford-bw** [comment]
> Gotcha, the empty tables don't look so good. Let's wait to merge this one until we get to DX-1106

Ah, funny enough I thought it looked bad _without_ the empty tables

**Comment by dtolb** [comment]
Not needed anymore

**Pull request closed without merging**
