### PR TITLE
add ratelimits about iris

### PR DESCRIPTION
**Pull request by dtolb**
## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `stop-gap-v2`

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-1193-update-iris-rate-limits.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-1193-update-iris-rate-limits.s3-website-us-east-1.amazonaws.com/

**Review by jmulford-bw — APPROVED** [review]
Looks good but I do have 2 questions.

1) Is there any value in documenting some of the actual rate limits? Like how many search method calls can you make in a minute
2) Do we have any endpoints that may not be rate limited? Should we put a generic "all endpoints may be rate limited" flag?

**Comment by dtolb** [comment]
> Is there any value in documenting some of the actual rate limits? Like how many search method calls can you make in a minute

Direction from SA is we don't want to expose our actual limits as it restricts our ability to change them w/o notice

> Do we have any endpoints that may not be rate limited? Should we put a generic "all endpoints may be rate limited" flag?

We do, it's not ideal, some will never return a 429 and we wanted to list specifically the ones that will return 429

**Pull request merged**
