### PR TITLE
Added basic recording guide

### PR DESCRIPTION
**Pull request by jmulford-bw**
## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `stop-gap-v2`

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-868.s3-website-us-east-1.amazonaws.com/

**Review by dtolb — CHANGES_REQUESTED** [review]
Really like the content! 

For each `### {verb}` before the example, add a `#### Use {verb} if:` section with a few bullet points for the use case.

So something like:

```md
#### Use <Record> if:

* You're capturing a voicemail
* You only need a single party recording
* You're capturing input that should pause the call until finished
```

And the same for the other `<StartRecording>` . 

The goal is let folks quickly look at this doc and get an idea of what verb to use as easily as possible.

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-868.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-868.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-868.s3-website-us-east-1.amazonaws.com/

**Pull request merged**
