### PR TITLE
TDP-4434: More edits for Conference as its own verb

### PR DESCRIPTION
**Pull request by n-miles**

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-tdp-4434-hotfix.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-tdp-4434-hotfix.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-tdp-4434-hotfix.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-tdp-4434-hotfix.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-tdp-4434-hotfix.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-tdp-4434-hotfix.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-tdp-4434-hotfix.s3-website-us-east-1.amazonaws.com/

**Review by muesono-daitan — APPROVED** [review]

**Pull request merged**
