### PR TITLE
decimals on time parameter had six digits, need only three

### PR DESCRIPTION
**Pull request by scapps-bw**
## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `stop-gap-v2`

## Brief Summary of changes

On GET /calls, the docs showed six decimals digits on time-related parameters, but we only provide three digits. So I fixed the docs to reflect reality.

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-decimals-on-seconds.s3-website-us-east-1.amazonaws.com/

**Review by n-miles — APPROVED** [review]

**Comment by mrmeyers99** [comment]
There are a bunch of other places that have 6 decimal places.  Search for `\d{6}Z"` in the repo with regex turned on

**Review by mrmeyers99 — CHANGES_REQUESTED** [review]
Please fix all places with 6 decimals.

**Review by mrmeyers99 — APPROVED** [review]

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-decimals-on-seconds.s3-website-us-east-1.amazonaws.com/

**Pull request merged**
