### PR TITLE
Edge 418: WebRTC guide and link to browser SDK

### PR DESCRIPTION
**Pull request by jturner-bw**

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-EDGE-418.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-EDGE-418.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-EDGE-418.s3-website-us-east-1.amazonaws.com/

**Comment by jturner-bw** [comment]
@jmulford-bw looks like I'm doing something wrong... my "Getting started" guide isn't getting rendered. Any ideas?

**Comment by jmulford-bw** [comment]
> @jmulford-bw looks like I'm doing something wrong... my "Getting started" guide isn't getting rendered. Any ideas?

Hey @jturner-bw I fixed this for you, you needed to add a link in `SUMMARY.md`

**Review by jmulford-bw — APPROVED** [review]
Looks good to me 👍

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-EDGE-418.s3-website-us-east-1.amazonaws.com/

**Pull request merged**
