### PR TITLE
Revert "Bwdb 11282"

### PR DESCRIPTION
**Pull request by gocab-bw**
Reverts Bandwidth/bandwidth.github.io#683

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
http://bw-gitbook-api-docs-revert-683-bwdb-11282.s3-website-us-east-1.amazonaws.com/

**Comment by jmulford-bw** [comment]
Is there a specific reason to revert the docs? Published too early?

**Review by jmulford-bw — APPROVED** [review]

**Comment by hamermike** [comment]
@gocab-bw This repo isn't public to external customers yet. As long as this will be released by that point you may not need to revert it.

**Comment by gocab-bw** [comment]
> Is there a specific reason to revert the docs? Published too early?

Customer communications team is asking whether we can show documentation in a way that the new stuff won't be effective until August 30 (so they can plan for it). So can't just overwrite what's currently there with new stuff.

**Comment by jmulford-bw** [comment]
> > Is there a specific reason to revert the docs? Published too early?
> 
> Customer communications team is asking whether we can show documentation in a way that the new stuff won't be effective until August 30 (so they can plan for it). So can't just overwrite what's currently there with new stuff.

Awesome, thanks for the context 🎉

**Pull request merged**
