### PR TITLE
EDGE-510 Fix missing path params in session/participant calls

### PR DESCRIPTION
**Pull request by jturner-bw**
We were missing /participants/{participantId} in some places in the session API

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-EDGE-510.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-EDGE-510.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-EDGE-510.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-EDGE-510.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-EDGE-510.s3-website-us-east-1.amazonaws.com/

**Review by dhelms-bw — APPROVED** [review]

**Pull request merged**
