### PR TITLE
break out about and config for notifications, update the templates

### PR DESCRIPTION
**Pull request by dtolb**
## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `stop-gap-v2`

## Brief Summary of changes

break out about and config for notifications, update the templates

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-1392-HTTP-guide.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-1392-HTTP-guide.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
Preview Changes at:
        http://bw-dev-DX-1392-HTTP-guide.s3-website-us-east-1.amazonaws.com/

**Review by jmulford-bw — APPROVED** [review]
I like the guide template 😄

**Review by jchavez443 — APPROVED** [review]

**Pull request merged**
