### PR TITLE
Add Banner to webrtc/about

### PR DESCRIPTION
**Pull request by ajrice6713**
## For the Committer

⚠️ Ensure that for this repo (**bandwidth.github.io**) that the pull request change is opened against the branch `stop-gap-v2`

### CODE REVIEW

**Comment by DX-Bandwidth** [comment]
http://bw-gitbook-api-docs-dx-2144.s3-website-us-east-1.amazonaws.com/

**Comment by DX-Bandwidth** [comment]
http://bw-gitbook-api-docs-dx-2144.s3-website-us-east-1.amazonaws.com/

**Review by psherk-bw — DISMISSED** [review]

**Comment by smckinnon-bw** [comment]
Since the old page included the API endpoint specifications themselves, as well as explanatory content, would it make sense to link to both the documentation and the API specification?

**Comment by DX-Bandwidth** [comment]
http://bw-gitbook-api-docs-dx-2144.s3-website-us-east-1.amazonaws.com/

**Review by psherk-bw — APPROVED** [review]

**Pull request merged**
